import { formulario } from "./formulario.js";

export async function router()
{
    const D=document,
    W=window,
    $Main=D.getElementById("main");
    let $formulario="";
    let {hash}=location;
    $Main.innerHTML="";
    if(hash==="#/mostrarFormulario")
    {
        $formulario=formulario([{
            nombre:"Nombre",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },{
            nombre:"Paterno",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$",
        },{
            nombre:"Materno",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$",
        }]);
        
    }
    else if(hash==="#/registrarMedicamento")
    {
        $formulario=formulario([{
            nombre:"Medicamento",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },{
            nombre:"Descripcion",
            type:"textarea",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        }]);
        
    }
    
    else if(hash==="#/registrarReceta")
    {
        $formulario=formulario([{
            nombre:"Observaciones",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        }]);
    }
    if(hash==="#/registrarConsulta")
    {
        $formulario=formulario([{
            nombre:"Observaciones",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Motivo",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Via Ingreso",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Remision",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Fecha",
            type:"datetime-local",
            pattern:""
        },
        {
            nombre:"Observaciones",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Diagnostico",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        }]);
    }
    if(hash==="#/registrarDoctor")
    {
        $formulario=formulario([{
            nombre:"Matricula",
            type:"number",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Nombre",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Paterno",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Materno",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Nombres",
            type:"datetime-local",
            pattern:""
        },
        {
            nombre:"Especialidad",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Direccion",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },{
            nombre:"Celular",
            type:"number",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Direccion",
            type:"Cedula",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"}
        ]);
    }
    if(hash==="#/registrarPaciente")
    {
        $formulario=formulario([{
            nombre:"Cedula",
            type:"number",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Nombre",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Paterno",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Materno",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Nombres",
            type:"datetime-local",
            pattern:""
        },
        {
            nombre:"Direccion",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },{
            nombre:"Nacimiento",
            type:"date",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Celular",
            type:"Cedula",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"}
        ]);
    }
    if(hash==="#/registrarUsuario")
    {
        $formulario=formulario([{
            nombre:"Usuario",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Contraseña",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"email",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        }]);
    }
    if(hash==="#/registrarAntecedente")
    {
        $formulario=formulario([{
            nombre:"Antecedentes_No_Patologicos",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Antecedentes_Patologicos",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Antecedentes_Familiares",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Antecedentes_Psicosociales",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },
        {
            nombre:"Antecedentes_Preexistentes",
            type:"text",
            pattern:"^[A-Za-zÑñáéíóú\\s]+$"
        },]);
    }
    $Main.appendChild($formulario);
    
}